### ISSUE TITLE
Keep bar with brand in canvas, move only navigation-DIV and search off-canvas

### ISSUE THREAD

**Issue by cbieser** [iamphill/Bootstrap-Offcanvas#1]
You moved the toggle-button outside the nav.navbar. Is it posible to keep the nav.navbar with brand and move only the div#bs-navbar-offcanvas? See the bootstrap docs for Navbar with toggle-Button <http://getbootstrap.com/components/#navbar>

**Comment by marcandrews** [comment]
I think what @cbieser is trying to say is that you're not using standard Bootstrap markup.

In standard Bootstrap markup, the navbar toggle button is located inside the ```<nav>``` element; while your rep requires that it is located outside the ```<nav>``` element.

If you use your rep with standard Bootstrap markup, the entire navbar, along with the toggle, is hidden at smaller screen widths.

It would be ideal if your rep was compatible with standard Bootstrap markup and just used the ```<div class="collapse navbar-collapse">``` element as the content for the off-canvas navigation menu (instead of the entire ```<nav>``` element).

**Comment by marcandrews** [comment]
Also, keeping the navbar visible provides a better, more stable and more predictable user experience.
